-- AlterTable
ALTER TABLE "LeaveType" ADD COLUMN     "confirmationBonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "probationQuota" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "quarterlyLimit" INTEGER NOT NULL DEFAULT 0;
