name: Test Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: echo "Action triggered successfully"
